"""
Report generator for audit results.
Outputs Markdown, JSON, and PDF formats.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .rules import AuditResult, RiskLevel

logger = logging.getLogger(__name__)

RISK_EMOJI = {
    RiskLevel.CRITICAL: "🔴",
    RiskLevel.HIGH: "🟠",
    RiskLevel.MEDIUM: "🟡",
    RiskLevel.LOW: "🟢",
    RiskLevel.INFO: "🔵",
}


class ReportGenerator:
    """Generates audit reports in multiple formats."""

    def __init__(self, output_dir: str = "./reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        result: AuditResult,
        format: str = "markdown",
        filename: Optional[str] = None,
    ) -> Path:
        """Generate report in specified format."""
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        address_short = result.contract.address[:10]
        filename = filename or f"audit_{address_short}_{timestamp}"

        if format == "markdown":
            return self._generate_markdown(result, filename)
        elif format == "json":
            return self._generate_json(result, filename)
        else:
            raise ValueError(f"Unsupported format: {format}")

    def _generate_markdown(self, result: AuditResult, filename: str) -> Path:
        """Generate Markdown audit report."""
        c = result.contract
        lines = [
            f"# Smart Contract Audit Report",
            f"",
            f"**Contract:** `{c.address}`",
            f"**Chain:** {c.chain}",
            f"**Compiler:** {c.compiler_version or 'N/A'}",
            f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            f"",
            f"---",
            f"",
            f"## Risk Summary",
            f"",
            f"**Risk Score: {result.risk_score}/100 ({result.risk_level})**",
            f"",
        ]

        # Findings by severity
        for level in RiskLevel:
            level_findings = [f for f in result.findings if f.risk == level]
            if not level_findings:
                continue

            emoji = RISK_EMOJI[level]
            lines.append(f"### {emoji} {level.value.upper()} ({len(level_findings)})")
            lines.append("")

            for i, f in enumerate(level_findings, 1):
                lines.append(f"**{f.rule_id}: {f.title}** (confidence: {f.confidence:.0%})")
                lines.append(f"")
                lines.append(f"{f.description}")
                if f.recommendation:
                    lines.append(f"")
                    lines.append(f"> **Recommendation:** {f.recommendation}")
                lines.append(f"")

        # Proxy info
        if c.is_proxy:
            lines.extend([
                "## Proxy Analysis",
                "",
                f"- **Type:** Upgradeable Proxy (EIP-1967)",
                f"- **Implementation:** `{c.implementation_address}`",
                f"- **Admin:** `{c.owner_address or 'Not detected'}`",
                "",
            ])

        # Functions
        if c.all_functions:
            lines.extend([
                "## Contract Functions",
                "",
                "```",
                *[f"  {fn}" for fn in c.all_functions[:30]],
                "```",
                "",
            ])

        # Footer
        lines.extend([
            "---",
            "",
            "*Generated by Smart Contract Auditor Agent (Hermes Orchestrator)*",
            f"*LLM-enhanced analysis powered by multi-model ensemble*",
        ])

        path = self.output_dir / f"{filename}.md"
        path.write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Markdown report saved: {path}")
        return path

    def _generate_json(self, result: AuditResult, filename: str) -> Path:
        """Generate JSON audit report."""
        data = {
            "contract": result.contract.address,
            "chain": result.contract.chain,
            "risk_score": result.risk_score,
            "risk_level": result.risk_level,
            "summary": result.summary,
            "is_proxy": result.contract.is_proxy,
            "implementation": result.contract.implementation_address,
            "findings": [
                {
                    "rule_id": f.rule_id,
                    "title": f.title,
                    "description": f.description,
                    "risk": f.risk.value,
                    "confidence": f.confidence,
                    "recommendation": f.recommendation,
                }
                for f in result.findings
            ],
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generator": "Smart Contract Auditor Agent v0.1.0",
        }

        path = self.output_dir / f"{filename}.json"
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
        logger.info(f"JSON report saved: {path}")
        return path

    def generate_batch_summary(self, results: list[AuditResult]) -> Path:
        """Generate summary report for batch scans."""
        lines = [
            "# Batch Audit Summary",
            "",
            f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            f"**Contracts Scanned:** {len(results)}",
            "",
            "## Results Overview",
            "",
            "| # | Contract | Chain | Risk Score | Level | Findings |",
            "|---|----------|-------|------------|-------|----------|",
        ]

        for i, r in enumerate(results, 1):
            emoji = RISK_EMOJI.get(r.risk_level.lower() if isinstance(r.risk_level, str) else r.risk_level, "")
            lines.append(
                f"| {i} | `{r.contract.address[:10]}...` | {r.contract.chain} | "
                f"{r.risk_score} | {r.risk_level} | {len(r.findings)} |"
            )

        lines.extend(["", "---", "", "*Generated by Smart Contract Auditor Agent*"])

        path = self.output_dir / "batch_summary.md"
        path.write_text("\n".join(lines), encoding="utf-8")
        return path
